<?php
$fav_songs = [
"A Little Late",
"Across the Caves",
"Adelina",
"Aging",
"Alabama Movies",
"All the Choices",
"Arms & Opinions",
"Baby on My Birthday",
"Beautiful Stranger (Cover)",
"Benny Once Told Me",
"Black Sky",
"Blue Obvious",
"Blunderland",
"Booster Seat",
"Break Your High",
"Butterflies",
"Camelot",
"Carrots",
"Charlie's Brother",
"Chipper on Ezastar",
"Classless Act",
"Cosmetic Skull",
"Dead Friends",
"Don't Leave Me Gravity",
"Don't",
"Double Decker",
"Flatwound Strings",
"Flyer",
"For the View",
"Free Will At Ease",
"Girls Night",
"Hail Mary",
"Hey Sweet",
"Hickey King",
"Hollywood Factory",
"How Stuck You Are",
"Hush Now",
"I Am Sam",
"I'm Sorry for Always Apologizing",
"In My Head",
"Intro",
"Ira",
"Kick",
"Lily",
"Little Girl Blue and The Battle Envy",
"Long Ride",
"Lost Wonderfuls",
"Louder in Outer Space",
"Magnifying Glass",
"Man Out There",
"Mars",
"Masquerade",
"Me and Doll",
"Morning Dew",
"Mostly Glad",
"Mr. Proper English Man",
"Not Going Back Again",
"Nothing More Than a Body",
"Number 4",
"Oddie Moore",
"Oh Well, We'll Win",
"Party House",
"Perfume for Now",
"Picker of His Words",
"Placer",
"Play House",
"Play",
"Pretective Boy",
"Queen For A Day",
"Rabbit Food",
"Rainbows",
"Sammy Was a Psycho",
"Scummy Summer",
"Seeing the World",
"Send a Priest",
"Singalong",
"Someone Like a Friend",
"Stop Digging",
"Tear of Rivers",
"They're Cheap (I'm Free)",
"This Vacation",
"Tiger at the Drugstore",
"Ugly",
"Van Gogh",
"When We're Apart",
"Will Cut You",
"Your Honor"
];

$fav_albums = [
    "Taking Over the World",
    "Lost Wonderfuls",
    "Fuzz Steilacoom",
    "The Big Fit",
    "The Make It All Show",
    "Chaos County Line"
];
$fav_videos = [
    "A Little Late",
"Across The Caves",
"Alabama Movies",
"Arms & Opinions",
"Camelot",
"Classless Act",
"Cosmetic Skull",
"Don't Leave Me Gravity",
"For the View",
"Free Will At Ease",
"Hail Mary",
"Hey Sweet",
"Hickey King",
"Hollywood Factory",
"I'm Sorry For Always Apologizing",
"Little Girl Blue and The Battle Envy",
"Louder In Outer Space",
"Morning Dew",
"Nothing More Than a Body",
"Oddie Moore",
"Perfume For Now",
"Picker of His Words",
"Play House",
"Pretective Boy",
"Queen For A Day",
"Rabbit Food",
"Stop Digging",
"They're Cheap (I'm Free)",
"Tiger At The Drugstore",
"Ugly"
];

$profile_prompts = [
    "Favorite movie",
    "Favorite game",
    "Best concert you’ve ever seen",
    "Your nickname growing up",
    "Favorite SP lyric",
    "The pet you’d bring on tour",
    "Favorite book",
    "Favorite non-SP album",
    "Best way to kill time in the van",
    "Best road-trip snack",
    "Favorite SP show"
];
?>

